# ndarray

In [9]:
# p84 建立陣列
import numpy as np

print('--- 一維 ---')
a = np.array([1, 2, 3])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

print('--- 二維 ---')
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)

print('--- 三維 ---')
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

--- 一維 ---
[1 2 3]
1
(3,)
3
int64
--- 二維 ---
[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
--- 三維 ---
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8
int64


In [18]:
# p85 指定陣列的資料型態
import numpy as np

print()
a = np.array([1, 2, 3, 4])
print(a)
print(a.dtype)

print()
a = np.array([1, 2, 3, 4], np.int64)
print(a)
print(a.dtype)

print()
a = np.array([1, 2, 3, 4], dtype = float)
print(a)
print(a.dtype)

print()
a = np.array([1, 2, 3, 4], dtype = complex)
print(a)
print(a.dtype)

print()
b = np.array(a, dtype = float, copy = True)
print(b)
print(b.dtype)
# ComplexWarning: Casting complex values to real discards the imaginary part: 將複數轉換為實數丟棄虛部


[1 2 3 4]
int64

[1 2 3 4]
int64

[1. 2. 3. 4.]
float64

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128

[1. 2. 3. 4.]
float64


/Users/willy/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: ComplexWarning: Casting complex values to real discards the imaginary part


In [30]:
# p86 自訂結構型態
import numpy as np

# int8, int16, int32, int64 可用'i1', 'i2', 'i4', 'i8' 代替 (可用縮寫)
# float16, float32, float64 可用'f1'', 'f2', 'f3', 'f4' 代替

dt = np.dtype('f2')
print(dt)

print()
people = np.dtype([('name', 'S20'), ('height ', 'i4'), ('weight', 'f2')])
# string 20 bytes, int 4 bytes, floor 2 bytes

a = np.array([('amy', 156, 50), ('bob', 175, 72)], dtype = people)
print(a)
print(a['name'])

float16

[(b'amy', 156, 50.) (b'bob', 175, 72.)]
[b'amy' b'bob']
