# ndarray

In [9]:
# p84 建立陣列
import numpy as np

print('--- 一維 ---')
a = np.array([1, 2, 3])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

print('--- 二維 ---')
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)

print('--- 三維 ---')
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

--- 一維 ---
[1 2 3]
1
(3,)
3
int64
--- 二維 ---
[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64
--- 三維 ---
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8
int64


In [30]:
# p85 指定陣列的資料型態
import numpy as np

print()
a = np.array([1, 2, 3, 4])
print(a)
print(a.dtype)

print()
a = np.array([1, 2, 3, 4], np.int64)
print(a)
print(a.dtype)

print()
a = np.array([1, 2, 3, 4], dtype = float)
print(a)
print(a.dtype)

print()
a = np.array([1, 2, 3, 4], dtype = complex)
print(a)
print(a.dtype)

print()
b = np.array(a, dtype = float, copy = True)
print(b)
print(b.dtype)
# ComplexWarning: Casting complex values to real discards the imaginary part: 將複數轉換為實數丟棄虛部


[1 2 3 4]
int64

[1 2 3 4]
int64

[1. 2. 3. 4.]
float64

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128

[1. 2. 3. 4.]
float64


/Users/willy/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: ComplexWarning: Casting complex values to real discards the imaginary part


In [30]:
# p86 自訂結構型態
import numpy as np

# int8, int16, int32, int64 可用'i1', 'i2', 'i4', 'i8' 代替 (可用縮寫)
# float16, float32, float64 可用'f1'', 'f2', 'f3', 'f4' 代替

dt = np.dtype('f2')
print(dt)

print()
people = np.dtype([('name', 'S20'), ('height ', 'i4'), ('weight', 'f2')])
# string 20 bytes, int 4 bytes, floor 2 bytes

a = np.array([('amy', 156, 50), ('bob', 175, 72)], dtype = people)
print(a)
print(a['name'])

float16

[(b'amy', 156, 50.) (b'bob', 175, 72.)]
[b'amy' b'bob']


In [7]:
# p87 變換陣列的形狀排列與維度

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a_2d = a.reshape(3, 4) # (row, col)
print(a_2d)

print('----------')
a_3d = a.reshape(3, 2, 2)
print(a_3d)

print('----------')
a_2d_col = a.reshape(3, 4, order='F') # order方向: 預設為水平, F為垂直
print(a_2d_col)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
----------
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [10]:
# p88 從數值範圍建立陣列
import numpy as np
a = np.arange(12)
print(a)

print('----------')
a = np.arange(12).reshape(4,3)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
----------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [14]:
# p89 等差數列(linspace) 與等比數列(logspace)

import numpy as np

a = np.linspace(10, 20, 5, endpoint = False) # (10~20之間, 產生5個等距的數字; endpoint=浮點數)
print(a)

print('----------')
b = np.linspace(0, 2, 9).reshape(3, 3)
print(b)
          
print('----------')
c = np.logspace(0, 9, 10, base=2, dtype='i4').reshape(2,5) # base=基數; i4 int32
print(c)

[10. 12. 14. 16. 18.]
----------
[[0.   0.25 0.5 ]
 [0.75 1.   1.25]
 [1.5  1.75 2.  ]]
----------
[[  1   2   4   8  16]
 [ 32  64 128 256 512]]


In [29]:
# p90 陣列填值

import numpy as np

a = np.zeros([2,3])
print(a)

print('----------')
b = np.ones([2,3])
print(b)

c = np.array([[1,2,3],[4,5,6]])
print(c)

c0 = np.zeros_like(c) # 根據c的形狀
print(c0)

c1 = np.ones_like(c)
print(c1)

print('----------')
d = np.random.random((2,3)) # 產生隨機數字
print(d)

e = np.empty([2,2])  # 產生記憶體中的數字
print(e)

e1 = np.empty_like(c) # 將e如c的形狀顯示
print(e1)

print('----------')
f = np.eye(3, dtype = int) # 對角線填1, 其他填0
print(f)

f1 = np.eye(3, k = 1) # 將f往右偏1個位置
print(f1)

[[0. 0. 0.]
 [0. 0. 0.]]
----------
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
----------
[[0.68976779 0.46015511 0.05462804]
 [0.42250422 0.27425319 0.81043115]]
[[ 0.00000000e+000  4.94065646e-324]
 [ 1.73059937e-077 -4.33574101e-311]]
[[4604388095434492416 4601961037385652062 4588033552004518160]
 [4601282779299499664 4598612126148514104 4605474934363027558]]
----------
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [41]:
# p91 陣列切片

import numpy as np

a = np.arange(6) # 一維陣列
print(a)
print(a[2:-1])
print(a[::2]) # [start, end, 間隔]

print('----------')
a = np.array([[11,12,13],[23,24,25],[34,35,36]]) # 二維陣列
print(a)
print(a[1])
print('- - - - - -')
print(a[1][1:])

print('----------')
print(a[...,1]) # ...代表省略
print(a[1,...])
print(a[...,1:])

[0 1 2 3 4 5]
[2 3 4]
[0 2 4]
----------
[[11 12 13]
 [23 24 25]
 [34 35 36]]
[23 24 25]
- - - - - -
[24 25]
----------
[12 24 35]
[23 24 25]
[[12 13]
 [24 25]
 [35 36]]


In [52]:
# p92 二維陣列的索引

import numpy as np

a = np.arange(0,36).reshape(6,6)
print(a)

print('----------')
print(a[4,5])
print(a[4,-1])

print('----------')
print(a[3, 1:4])

print('----------')
print(a[:3, 3:])

print('----------')
print(a[2,:])

print('----------')
print(a[:,3])

print('----------')
print(a[:,::2]) # 是col向量,但python是橫向列出

print('----------')
print(a[::2, ::3])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
----------
29
29
----------
[19 20 21]
----------
[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]
----------
[12 13 14 15 16 17]
----------
[ 3  9 15 21 27 33]
----------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]
 [30 32 34]]
----------
[[ 0  3]
 [12 15]
 [24 27]]


In [67]:
# p93 三維陣列的索引

import numpy as np

a = np.arange(16).reshape(2,2,4) # 2個 2x4的矩陣
print(a)

print('----------')
print(a[0])

print('----------')
print(a[0, :, 1:3])

print('----------')
print(a[0, 1, :-1]) # : -1最後一個不算 like (1:5)是1,2,3,4

print('----------')
print(a[0, 1]) # 陣列索引

print('----------')
print(a[0][1]) # 切片擷取(上面的另一種寫法)

print('----------')
print(a[0, 1, 2]) # 陣㓚索引

print('----------')
print(a[0][1][2]) # 切片擷取(上面的另一種寫法)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
----------
[[0 1 2 3]
 [4 5 6 7]]
----------
[[1 2]
 [5 6]]
----------
[4 5 6]
----------
[4 5 6 7]
----------
[4 5 6 7]
----------
6
----------
6


In [76]:
# p94 陣列索引的其他方式

import numpy as np

x = np.arange(25).reshape(5,5)
print(x)

print('----------')
print(x[[0, 1, 2], [0, 1, 0]]) # 取(0, 0) (1, 0) (2, 0)

print('----------')
print(x[[2, 4]]) # 取row 2 4

print('----------')
print(x[ x > 20])
print(x[ x % 2 == 0])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
----------
[ 0  6 10]
----------
[[10 11 12 13 14]
 [20 21 22 23 24]]
----------
[21 22 23 24]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


In [87]:
# p95 陣列與共用記憶體

import numpy as np

a = np.arange(7)
print('a: ', a)

b = a[2:6]
print('b: ', b)

print('----------')
c = a[2:6].copy()
print('c: ', c)

print(np.may_share_memory(a, b)) # b與a共用記憶體
print(np.may_share_memory(a, c)) # c是複製a

print('----------')
b[0] = 20 # 因為共用記憶體, 所以b改變, a也改變了
print(a)

a:  [0 1 2 3 4 5 6]
b:  [2 3 4 5]
----------
c:  [2 3 4 5]
True
False
----------
[ 0  1 20  3  4  5  6]


In [93]:
# p96~p97 廣播_對不同形狀的陣列進行陣列計算

import numpy as np

a = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
print(a)

print('----------')
b = np.random.randint(1, 3, 8).reshape(2 ,4)
print(b)

print('----------')
print(a*b) # 形狀一樣，對應位置相乘

print('----------')
print('----------')
c = np.array([1, 2]).reshape(2, 1)
print(c)

print('----------')
print(a*c) # 乘法廣播

d = np.array([1, 1, 1, 1]) # 加法廣播
print(a + d)

[[1 2 3 4]
 [4 5 6 7]]
----------
[[1 2 2 2]
 [2 1 1 2]]
----------
[[ 1  4  6  8]
 [ 8  5  6 14]]
----------
----------
[[1]
 [2]]
----------
[[ 1  2  3  4]
 [ 8 10 12 14]]
[[2 3 4 5]
 [5 6 7 8]]


In [105]:
# p95 矩陣計算_位置相加

a = np.arange(6).reshape(2, 3)
print(a)
      
print('----------')
print(a + 5) # 每個位置+5

print('----------')
b = np.ones(6, dtype = int).reshape(2, 3)
print(b)
print('- - - - - ')
print(a + 2 * b) # b為每個位置是1, *2後為每個位置是2, 再加a

[[0 1 2]
 [3 4 5]]
----------
[[ 5  6  7]
 [ 8  9 10]]
----------
[[1 1 1]
 [1 1 1]]
- - - - - 
[[2 3 4]
 [5 6 7]]


In [109]:
# p96 矩陣計算_內積與轉置

a = np.arange(6).reshape(3, 2)
print(a)

print('----------')
b = np.arange(6).reshape(2, 3)
print(b)

print('----------')
c = np.dot(a, b) # 參考講義p24
print(c)

print('----------')
print(c.T) # 矩陣轉置

[[0 1]
 [2 3]
 [4 5]]
----------
[[0 1 2]
 [3 4 5]]
----------
[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]
----------
[[ 3  9 15]
 [ 4 14 24]
 [ 5 19 33]]


In [130]:
# p100 內建函數

import numpy as np

a = np.arange(6)
print(a, type(a))
print(a.sum())
print(a.mean())
print(a.std())
print('a.min: ', a.min())
print(a.max())
print('a.argmin: ', a.argmin()) # 最小值的位置, 參考備註
print(a.argmax())
print(np.cos([0, np.pi, 2*np.pi])) # np.pi = 3.141592653589793
print(np.exp([1, 2, 3])) # exp為自然常數2.71828
print(np.sqrt([1, 4, 9, 16])) # sqrt為開根號

'''備註
argmax(a, axis=None, out=None)
a 表示array
axis 表示指定的軸, 默認是None, 表示把array平鋪
out 默認為None, 如果指定, 返回的结果會插入其中'''

a = np.array([[2,5,6],[7,6,1]])
print(np.argmax(a))
# 輸出结果為3, 因為a裡面7是最大的, 但没有指定axis, 默認是None, 相當於把array平鋪為[2,5,6,7,6,1], 结果就是3，因為索引3對應的值最大

print('----------')
b = np.array([1, 2, 3, 4, 5])
print('b: ', b, type(b))
print('b.argmin: ', b.argmin())
print('b.min: ', b.min())

[0 1 2 3 4 5] <class 'numpy.ndarray'>
15
2.5
1.707825127659933
a.min:  0
5
a.argmin:  0
5
[ 1. -1.  1.]
[ 2.71828183  7.3890561  20.08553692]
[1. 2. 3. 4.]
3
----------
b:  [1 2 3 4 5] <class 'numpy.ndarray'>
b.argmin:  0
b.min:  1


In [136]:
# 102存檔

import numpy as np
a = np.random.randint(1, 20, 16).reshape(4, 4) # 建立1~20隨機16個數字旳4x4矩陣
print(a)

print('----------')
b = np.sort(a, axis = 0)
print(b)

print('----------')
c = np.sort(b, axis = 1) # 依據b按col順序排列
print(c)

# np.save('c', c) # save(檔名，要存的矩陣)
# np.savetxt('c', c) # 存成txt檔(無法load回來)
# d = np.load('c.npy') # load檔案

[[14 16 12 16]
 [15  8 11 18]
 [ 1  3  4  7]
 [18  1  5 15]]
----------
[[ 1  1  4  7]
 [14  3  5 15]
 [15  8 11 16]
 [18 16 12 18]]
----------
[[ 1  1  4  7]
 [ 3  5 14 15]
 [ 8 11 15 16]
 [12 16 18 18]]
